server:
  port: 8979
  servlet:
    session:
      timeout: P30D  # 默认30天

spring:
  application:
    name: pigeon
  profiles:
    active: pro
    include: business


  servlet:
    multipart:
      max-file-size: 50MB

  datasource:
    url: jdbc:mysql://122.152.217.190:3306/pigeon?useUnicode=true&characterEncoding=utf-8
    username: root
    password: "OwenHi2019!"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      connection-init-sql: SET NAMES utf8mb4

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  jackson:
    date-format: ${spring.mvc.date-format}
    time-zone: Asia/Shanghai

  session:
    store-type: redis
    redis:
      namespace: ${spring.application.name}
      flush-mode: on_save

  redis:
    host: 122.152.217.190
    password: OwenHi
    port: 6379
    database: 3
    lettuce:
      pool:
        max-active: 50
        max-idle: 5
        max-wait: -1s
        min-idle: 1

  messages:
    basename: config/messages

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  autoDialect: true
  closeConn: true
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql





swagger:
  enable: true

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error


